# This file was generated by GoReleaser. DO NOT EDIT.
class Sshh < Formula
  desc "ssh hosts manager"
  homepage "https://github.com/sakoken/sshh"
  url "https://github.com/sakoken/sshh/releases/download/v0.0.11/sshh_0.0.11_macOS_64-bit.zip"
  version "0.0.11"
  sha256 "461aefa67c81e4769e39d72110b8e25cded4125a1872877b505ec32d99256956"

  def install
    bin.install "sshh"
  end
end
